---
title: "CodeRUs_module6"
author: "CodesRUs"
date: "10/24/2021"
output: html_document
bibliography: 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction
The ability to maintain constant internal temperature is a crucial skill for birds and mammals. Our brain and neural network only function at the ideal temperature range. (@morrison2019central) However, all mammals engage in some types of heterothermy, either regional or temporal, to modulate the metabolic demand or better survive in certain environments.(@mitchell2002adaptive) In this module, we use a EDT 11 sensor to measure the change of temperature in the human body both during the day, and during the night (on few hours of sleep), to find the relationship between temperature difference and body mass. Also, we use downloaded data to find the relationship between temperature difference and body mass across a range of different mammals. To analyze these relationships, we created linear models (and logarithmic transformations) based on the temperature measurement and body mass by ggplot in R-studio. 

## Methods
To collect body temperature in the subject of our team, a simple temperature recording data-acquisition system (DAQ) is assembled using an Elegoo Arduino clone and DHT11 sensor; 15 minutes of axial temperature reading was recorded in daytime and early in the morning respectively. To evaluate scaling relationship between mean temperature difference and mass within human subjects, we filtered out outlying data and constructed a linear model using ggplot. To analyze inter-specific relationship, we combined human data with 51 non-human mammals data and applied the same linear model.

## Results

Our results show that there is no apparent relationship between body temperature difference and mass within human subjects.  There is a slight downward trend, in the data; meaning as mass increases, the difference in mean temperatures slightly decreases. The slope of the graph just slightly negative initially, and close to zero after the log transformation. 

When the human data is combined with other mammalian data, a negative scaling between mean body temperature difference and mass was found. As the mass of the mammal increases, the difference between the mean temperatures decreases as well. Both of these graphs create line of best fits with negative slopes. 


## Discussions

In humans specifically, the data provided no clear relationship between mass and mean body temperature difference. This would be an allometric growth relationship as the change in mass does not equal the change in the difference in mean temperatures. The data helps to demonstrate that there are stable mechanisms controlling heat loss in humans and these appear to be for the most part consistent across individual human subjects as mass does not greatly differ. Within a small range of masses, we have similar metabolic rates further demonstrating the stability of human body temperature.


When the human data is combined with other mammalian species, a negative relationship is seen. While not a perfectly isometric relationship since the changes in the magnitude of mass and temperature are not directly equal, it is far closer than that of the data consisting of only humans.This demonstrates that the control of temperature oscillations does in fact vary across different mammalian species. Similar studies have been carried out in all different types of mammals and have shown that there is a complex relationship between metabolic rate, body mass, and body temperature. This aligns with our data as we do not see a strong relationship when specifically looking at the human species, but we see a more prominent relationship when data from many mammalian species are combined. 


## Contributions

## References
