---
title: "Project 7"
author: "CodesRUs"
date: "11/3/2021"
output: html_document
bibliography: BIOL3140.bib
---

### Introduction
When conducting comparative analyses on traits measured from related species, phylogenetic structures are not always taken in consideration, one reason being that phylogenetic comparative models might overlook the importance of abrupt shifts in traits produced by singular events (@garamszegi2014modern). In order to find out whether phylogenetic signals are indeed present in the Tb/body mass relationship of different species or not, we reexamined the data from Mortola and Lanthier (2004) using Pagel’s lamba, and compared the scaling of Tb variables between the ones we applied with the best fitted PGLS and the original results from Mortola and Lanthier (2004).

### Methods
In this study, we try to produce a phylogenetically corrected model measuring the relationship between body mass and temperature in different species. We first produce a linear model of T.high, T.low, and T.diff to find the best fit. Then, we use Pagel’s Lambda to find significant phylogenetic signals and p-value. After we find the significance of four variables, we apply PLGS analysis and log-transformed with Brownian model/Ornstein-Uhlenbeck (OU) models to evaluate character evolution over a phylogenetic tree. We find the best fit model from BM and OU model by calculating the AIC score. At the end of the project, we perform ANOVA test to compare the significance between our best fit model and Montrola’s model.
